version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/p4g4rm3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}{{ checksum "package-lock.json" }}
            - v1-dependencies
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
