version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/p4g4rm3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}{{ checksum "package-lock.json" }}
            - v1-dependencies
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test

  sonarqube:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
         name: Sonar Stuff
         command: |
           wget -c https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
           unzip sonar-scanner-cli-3.2.0.1227-linux.zip -d /tmp
           PATH=$PATH:/tmp/sonar-scanner-3.2.0.1227-linux/bin
           sonar-scanner -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.projectKey=$SONARQUBE_PROJECTKEY -Dsonar.host.url=$SONARQUBE_URL -Dsonar.sources=. -X

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - sonarqube
